#title in header
title: "Hi,"

#main info
#owner
owner: "I am Muhammad Firdaus"
email: firdaus.ex19@gmail.com
info: "Software Engineer from Indonesia ğŸ‡®ğŸ‡©"
#description
desc: "A man who explores his hobbies. ask, seek and experiment ğŸ˜"

#menu
menu:
  Tulisan: /archives
  Works: /Works
  About: /tentang

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/mdaushi
linkedin: https://linkedin.com/in/muhammad-firdaus-75948a137/
twitter: https://twitter.com/firdausspace
instagram: https://www.instagram.com/mhmdfiirdaus/
stackoverflow: https://stackoverflow.com

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
